"""empty message

Revision ID: 0bd391570c76
Revises: c66d6a1f4ae3
Create Date: 2025-01-30 16:42:53.849354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bd391570c76'
down_revision = 'c66d6a1f4ae3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compare_name', sa.String(length=256), nullable=False))
        batch_op.create_index(batch_op.f('ix_vendor_compare_name'), ['compare_name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_compare_name'))
        batch_op.drop_column('compare_name')

    # ### end Alembic commands ###
