"""empty message

Revision ID: 452d8b9e5cb8
Revises: f91d7e52e949
Create Date: 2025-01-18 03:07:26.654302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '452d8b9e5cb8'
down_revision = 'f91d7e52e949'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_action', schema=None) as batch_op:
        batch_op.add_column(sa.Column('errors', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_action', schema=None) as batch_op:
        batch_op.drop_column('errors')

    # ### end Alembic commands ###
