"""empty message

Revision ID: 4a83433bea20
Revises: cff29ea409eb
Create Date: 2025-02-04 16:18:46.433335

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime, timezone
from sqlalchemy.sql import table, column

# revision identifiers, used by Alembic.
revision = '4a83433bea20'
down_revision = 'cff29ea409eb'
branch_labels = None
depends_on = None

user_table = table('user',
    column('id', sa.Integer),
    column('created_at', sa.DateTime)
)

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    op.execute(
        user_table.update().values(created_at=datetime(2025,1,1,tzinfo=timezone.utc))
    )

    # Now make the column NOT NULL
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('created_at', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
