"""town, state, shopify_vendor tables

Revision ID: 7f8a77e01c6f
Revises: df341f2a1be6
Create Date: 2025-02-12 23:37:54.920420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f8a77e01c6f'
down_revision = 'df341f2a1be6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopify_vendor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_state_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_state_name'), ['name'], unique=True)

    op.create_table('town',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['state.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'state_id')
    )
    with op.batch_alter_table('town', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_town_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_town_state_id'), ['state_id'], unique=False)

    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('towns_shopify', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('town_id', sa.Integer(), nullable=False))
        batch_op.alter_column('total_products',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('total_variants',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index('ix_vendor_estado')
        batch_op.drop_index('ix_vendor_pueblo')
        batch_op.create_index(batch_op.f('ix_vendor_town_id'), ['town_id'], unique=False)
        batch_op.create_foreign_key(None, 'town', ['town_id'], ['id'])
        batch_op.drop_column('pueblo')
        batch_op.drop_column('pueblos_estados_shopify')
        batch_op.drop_column('estado')

    # ### end Alembic commands ###


def downgrade(): # TODO this script fails on an empty db. Why?
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pueblos_estados_shopify', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pueblo', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_vendor_town_id'))
        batch_op.create_index('ix_vendor_pueblo', ['pueblo'], unique=False)
        batch_op.create_index('ix_vendor_estado', ['estado'], unique=False)
        batch_op.alter_column('total_variants',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('total_products',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('town_id')
        batch_op.drop_column('towns_shopify')

    with op.batch_alter_table('town', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_town_state_id'))
        batch_op.drop_index(batch_op.f('ix_town_name'))

    op.drop_table('town')
    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_state_name'))
        batch_op.drop_index(batch_op.f('ix_state_code'))

    op.drop_table('state')
    op.drop_table('shopify_vendor')
    # ### end Alembic commands ###
