"""estado, pueblo tables

Revision ID: 8a32e5fa8f15
Revises: df341f2a1be6
Create Date: 2025-02-12 13:20:05.059631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a32e5fa8f15'
down_revision = 'df341f2a1be6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('estado', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_estado_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_estado_name'), ['name'], unique=True)

    op.create_table('pueblo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('estado_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['estado_id'], ['estado.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'estado_id')
    )
    with op.batch_alter_table('pueblo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pueblo_estado_id'), ['estado_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pueblo_name'), ['name'], unique=False)

    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shopify_names', sa.String(length=1024), nullable=False))
        batch_op.add_column(sa.Column('pueblos_shopify', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('pueblo_id', sa.Integer(), nullable=False))
        batch_op.alter_column('total_products',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('total_variants',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index('ix_vendor_estado')
        batch_op.drop_index('ix_vendor_pueblo')
        batch_op.create_index(batch_op.f('ix_vendor_pueblo_id'), ['pueblo_id'], unique=False)
        batch_op.create_foreign_key(None, 'pueblo', ['pueblo_id'], ['id'])
        batch_op.drop_column('pueblos_estados_shopify')
        batch_op.drop_column('pueblo')
        batch_op.drop_column('estado')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pueblo', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pueblos_estados_shopify', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_vendor_pueblo_id'))
        batch_op.create_index('ix_vendor_pueblo', ['pueblo'], unique=False)
        batch_op.create_index('ix_vendor_estado', ['estado'], unique=False)
        batch_op.alter_column('total_variants',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('total_products',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('pueblo_id')
        batch_op.drop_column('pueblos_shopify')
        batch_op.drop_column('shopify_names')

    with op.batch_alter_table('pueblo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pueblo_name'))
        batch_op.drop_index(batch_op.f('ix_pueblo_estado_id'))

    op.drop_table('pueblo')
    with op.batch_alter_table('estado', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_estado_name'))
        batch_op.drop_index(batch_op.f('ix_estado_code'))

    op.drop_table('estado')
    # ### end Alembic commands ###
