"""empty message

Revision ID: b5b40ccfe858
Revises: 452d8b9e5cb8
Create Date: 2025-01-27 13:45:34.947451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5b40ccfe858'
down_revision = '452d8b9e5cb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=256), nullable=False),
    sa.Column('admin_action_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_action_id'], ['admin_action.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_admin_action_id'), ['admin_action_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_admin_action_id'))

    op.drop_table('file')
    # ### end Alembic commands ###
