"""empty message

Revision ID: c66d6a1f4ae3
Revises: b5b40ccfe858
Create Date: 2025-01-30 12:05:38.555656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c66d6a1f4ae3'
down_revision = 'b5b40ccfe858'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_name'))

    op.drop_table('vendor')
    # ### end Alembic commands ###
