"""vendors       pueblo, estado (as strings)

Revision ID: cff29ea409eb
Revises: edc2a8ddb6ff
Create Date: 2025-02-01 03:27:04.229385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cff29ea409eb'
down_revision = 'edc2a8ddb6ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pueblo', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('estado', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('pueblos_estados_shopify', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_vendor_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_pueblo'), ['pueblo'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_pueblo'))
        batch_op.drop_index(batch_op.f('ix_vendor_estado'))
        batch_op.drop_column('pueblos_estados_shopify')
        batch_op.drop_column('estado')
        batch_op.drop_column('pueblo')

    # ### end Alembic commands ###
