"""empty message

Revision ID: deea039ff779
Revises: 4a83433bea20
Create Date: 2025-02-09 21:58:01.434462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deea039ff779'
down_revision = '4a83433bea20'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('user', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('failed_logins', sa.Integer(), nullable=False))

    # ### end Alembic commands ###

# -------------------------------------------------------------------------------------- #
    # THIS VERSION FAILED WITH NO RECORDS IN 'users'. Now it works?
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_logins', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

    op.execute("UPDATE user SET failed_logins = 0")

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('failed_logins', nullable=False)
# -------------------------------------------------------------------------------------- #


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('failed_logins')

    # ### end Alembic commands ###
