"""shopify_vendor name

Revision ID: e4f59d70b1b2
Revises: 7f8a77e01c6f
Create Date: 2025-02-13 01:03:51.377419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4f59d70b1b2'
down_revision = '7f8a77e01c6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopify_vendor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=256), nullable=False))
        batch_op.create_index(batch_op.f('ix_shopify_vendor_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopify_vendor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shopify_vendor_name'))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
